### ISSUE TITLE
Website not actually working

### ISSUE THREAD

**Issue by AdamHeal** [lolPants/beatsaver-reloaded#112]
I can’t believe I’m the first person to raise an issue as the website has been not working for 2/3 days at this point, but the title pretty much says it all. The website just isn’t working and I would appreciate it if someone gave a fuck.

**Comment by CL16kai** [comment]
yup

**Comment by luludotdev** [comment]
First off, you are not the first person to raise an issue, see #107 #109 #110. However it doesn't surprise me that you made this issue since if you managed to miss those issues, you must also be blind enough to not realise that I don't host `beatsaver.com`, as is clearly documented in this repo's [README](https://github.com/lolPants/beatsaver-reloaded#-legal-notice).
