### ISSUE TITLE
beatsaver thinks im using beatstage but im not

### ISSUE THREAD

**Issue by beaumonts** [lolPants/beatsaver-reloaded#115]
## Platform
**This bug report concerns:** *(select all that apply)*

[- ] Server

## Details
when i uploaded this song it thought i was using beatsage but im not using beatstage

## Reproducing the Problem
i dont know why this happened and i cant reproduce it

## Further Detail
https://beatsaver.com/beatmap/13033
![Cadfsdfsdfsdfsdfsdfpture](https://user-images.githubusercontent.com/69931499/105428809-0c8b9c00-5c05-11eb-9d3c-7d869d5859a1.PNG)
![Capture](https://user-images.githubusercontent.com/69931499/105428915-48befc80-5c05-11eb-9a11-8079f761776d.PNG)

**Comment by luludotdev** [comment]
The BeatSaver application didn't detect your beatmap as auto-generated by BeatSage as it only uses a rudimentary detection system. However it seems a `beatsaver.com` moderator manually reclassified your map, which isn't surprising since [Beat Sage's own verification](https://verify.beatsage.com/) tool reported your beatmap as "certainly" generated by Beat Sage.
