### ISSUE TITLE
Crash on any iOS device (Safari/Chrome) and Safari 11.1 (macOS)

### ISSUE THREAD

**Issue by n3tman** [lolPants/beatsaver-reloaded#15]
## Platform
**This bug report concerns:**
- [x] Client
- [ ] Server

## Details
Stack Trace:
```
f@https://beatsaver.com/src.4059cd8d.js:268:1068
https://beatsaver.com/src.4059cd8d.js:268:3493
_i@https://beatsaver.com/src.4059cd8d.js:74:77736
ro@https://beatsaver.com/src.4059cd8d.js:74:84866
ro@[native code]
lo@https://beatsaver.com/src.4059cd8d.js:74:85046
xa@https://beatsaver.com/src.4059cd8d.js:74:58481
xa@[native code]
https://beatsaver.com/src.4059cd8d.js:264:840
promiseReactionJob@[native code]
```
Probably because of some unsupported browser API, please check on https://caniuse.com/

## Reproducing the Problem
Open website on:
- Safari 11.1 on macOS High Sierra
- Safari on iPhone XS (iOS 12)
- Chrome on iPhone XS (iOS 12)
- Safari/Chrome on iPad Pro 12.9

## Further Detail
Screenshots from BrowserStack (real devices):

* iPhone XS
&nbsp;
— Safari
![2019-06-16_155012](https://user-images.githubusercontent.com/16892631/59564586-30622580-9051-11e9-9c66-83d8373fd517.png)
&nbsp;
— Chrome
![2019-06-16_155146](https://user-images.githubusercontent.com/16892631/59564587-30622580-9051-11e9-90e7-eea84cb5024d.png)

* iPad Pro 12.9
![2019-06-16_155227](https://user-images.githubusercontent.com/16892631/59564604-58ea1f80-9051-11e9-9e98-851e2a588338.png)
(Chrome has the same issue)

* macOS High Sierra
![2019-06-16_162605](https://user-images.githubusercontent.com/16892631/59564863-78cf1280-9054-11e9-9fc3-3ab1ee8efda8.png)
(**not reproduced** in Chrome or macOS Mojave / Safari 12)

**Comment by lolPants** [comment]
I can't test on Safari macOS or iOS, actual stacktraces from development are required for me to fix this.

**Comment by BaliBalo** [comment]
I was only able to test quickly the prod site using BrowserStack so I don't have the full proper stack trace, but here is the error I got:
`Can't find variable: IntersectionObserver`
Which seems to be caused by `react-intersection-observer` in BeatmapScroller: https://github.com/lolPants/beatsaver-reloaded/blob/master/client/src/ts/components/Beatmap/BeatmapScroller.tsx#L2

The IntersectionObserver API has only been made available in Safari [quite recently](https://caniuse.com/#feat=intersectionobserver) so I'm guessing a fair amount of Safari users still don't have access to it.

**Comment by BaliBalo** [comment]
Looks like there's an easy way to polyfill it: https://github.com/thebuilder/react-intersection-observer#polyfill
